---
- hosts: all
  tasks:
    - name: Configure apt-cacher-ng proxy
      become: true
      blockinfile:
        path: /etc/apt/apt.conf
        create: true
        mode: 0644
        block: |
          Acquire::http::Proxy "http://192.168.16.32:3142";
          Acquire::https::Proxy "DIRECT";
