- hosts: localhost
  gather_facts: False
  roles:
    - role: ara-report
    - role: htmlify-logs
    - role: merge-output-to-logs
    - role: upload-logs
      zuul_log_url: "https://logs.seanmooney.info"
