---
- hosts: all
  roles:
    - role: configure-mirrors
      pypi_mirror: "http://192.168.16.32:5000/simple"

- import_playbook: apt.yaml

- hosts: all
  tasks:
    - name: "install base packages"
      package:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - git
        - python3
    - name: Install acl
      when: ansible_os_family == "Debian"
      become: true
      apt:
        state: latest
        update_cache: true
        pkg:
          - acl # required for become to work

- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "https://minio-api.teim.app/zuul-logs"
      zuul_log_path_shard_build: false
    - log-inventory

- hosts: all
  roles:
    - start-zuul-console
    - ensure-output-dirs

- hosts: all
  roles:
    - validate-host
    - prepare-workspace-git
