---
- hosts: all
  tasks:
    - name: Ensure logs directory exists
      file:
        path: "{{ zuul.log_root }}/logs"
        state: directory
        mode: '0755'
    - name: Include Zuul manifest role
      include_role:
        name: generate-zuul-manifest
    - name: Upload logs to MinIO
      include_role:
        name: upload-logs-minio
      vars:
        upload_logs_s3_endpoint: "{{ zuul_log_targets.upload_logs_s3_endpoint }}"
        zuul_log_bucket: "{{ zuul_log_targets.zuul_log_bucket }}"
        zuul_log_aws_access_key: "{{ zuul_log_targets.zuul_log_aws_access_key }}"
        zuul_log_aws_secret_key: "{{ zuul_log_targets.zuul_log_aws_secret_key }}"
        zuul_log_create_indexes: "{{ zuul_log_targets.zuul_log_create_indexes | default(true) }}"
        zuul_log_bucket_public: "{{ zuul_log_targets.zuul_log_bucket_public | default(true) }}"
        upload_logs_s3_addressing_style: "{{ zuul_log_targets.upload_logs_s3_addressing_style | default('path') }}"
