---
- hosts: localhost
  tasks:
    - name: Include Zuul manifest role
      include_role:
        name: generate-zuul-manifest
    - name: Generate bulk log download script
      include_role:
        name: local-log-download
      vars:
        local_log_download_api: 'https://zuul.teim.app/api/tenant/{{ zuul.tenant }}'
    - name: Upload logs to MinIO
      include_role:
        name: upload-logs-minio
      vars:
        upload_logs_s3_endpoint: "{{ zuul_log_targets.upload_logs_s3_endpoint }}"
        zuul_log_bucket: "{{ zuul_log_targets.zuul_log_bucket }}"
        zuul_log_aws_access_key: "{{ zuul_log_targets.zuul_log_aws_access_key }}"
        zuul_log_aws_secret_key: "{{ zuul_log_targets.zuul_log_aws_secret_key }}"
        zuul_log_create_indexes: "{{ zuul_log_targets.zuul_log_create_indexes | default(true) }}"
        zuul_log_bucket_public: "{{ zuul_log_targets.zuul_log_bucket_public | default(true) }}"
        upload_logs_s3_addressing_style: "{{ zuul_log_targets.upload_logs_s3_addressing_style | default('path') }}"
    # NOTE(ianw): file generated by local-log-download, upload_results
    # is registered by the upload-logs-swift role
    - name: Register quick-download link
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: Download all logs
                url: 'download-logs.sh'
                metadata:
                  command: 'curl "{{ upload_results.url }}/download-logs.sh" | bash'
